FROM node:20

WORKDIR /code

# Install project dependencies
COPY package.json tsconfig.json /code/
RUN npm install
RUN npm install -g serve

# Build project
COPY src /code/src
RUN cd /code && npm run build

# Serve
CMD ["serve", "-s", "/code/build"]
