name: Tests CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  analyse:
    runs-on: ubuntu-latest
    name: "Analyse Code"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run TSC
        run: npx tsc
  test-unit:
    runs-on: ubuntu-latest
    name: "Run unit Tests"
    needs: analyse
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
  test-e2e:
    runs-on: ubuntu-latest
    name: "Run E2E Tests"
    needs: analyse
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build application
        run: npm run build:test
      - name: Start application
        env:
          WEB_API_URL: http://localhost:8080
        run: npm run preview &
      - name: Run Playwright tests
        run: npm run test:web:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
